version: '3'

volumes:
  pg_data:
  redmine_plugins:
  redmine_themes:
  redmine_data:
  
services:

  redmine:
    image: redmine:4.1.1-alpine
    container_name: redmine
    volumes:
            - ./redmine_plugins:/usr/src/redmine/plugins
            - ./redmine_themes:/usr/src/redmine/public/themes
            - ./redmine_data:/usr/src/redmine/files
         
    ports:
      - 8083:3000

    environment:
      REDMINE_DB_POSTGRES: "postgres"
      REDMINE_DB_USERNAME: "postgres"
      REDMINE_DB_PASSWORD: "redmine"
      REDMINE_DB_DATABASE: "redmine"
      REDMINE_SECRET_KEY_BASE: "..."

    restart: unless-stopped
    depends_on:
      - postgres

  postgres:
    image: postgres:10
    container_name: postgres_redmine
    volumes:
      - ./pg_data:/var/lib/postgresql/data

    environment:
      POSTGRES_PASSWORD: "redmine"
      POSTGRES_DB: "redmine"
      PGDATA: "/var/lib/postgresql/data"

    restart: unless-stopped
