version: "3"

networks:
  gitea:
    external: false

volumes:
  gitea:
    driver: local

services:
  server:
    image: gitea/gitea:1.13.2
    container_name: gitea
    #    environment:
    #     - USER_UID=1000
    #     - USER_GID=1000
    restart: always
    networks:
      - gitea
    volumes:
      - gitea:/data
        #      - /root/.ssh/:/data/git/.ssh
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "8080:3000"
      - "2221:22"
