version: '3'
networks:
  jenkins:
    external: false

volumes:
  jenkins:
    driver: local

services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    restart: unless-stopped
    networks:
      - jenkins
    privileged: true
    user: root
    ports:
      - 8081:8080
      - 50000:50000

    volumes:
      - ./jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/local/bin/docker:/usr/local/bin/docker
