version: '3'

volumes:
  mysql_data:

services:
  mysql:
   container_name: mysql
   image: mysql:latest
   restart: unless-stopped
   ports:
     - 3306:3306
   volumes:
     - ./mysql_data:/var/lib/mysql
   environment:
     MYSQL_DATABASE: 'db'
     MYSQL_ROOT_PASSWORD: 'asdzxcfv'
     MYSQL_USER: 'el'
     MYSQL_PASSWORD: 'asdxzcfv'
