version: '3'

networks:
  mysql:

volumes:
  mysql_data:

services:
  mysql:
   container_name: mysql
   image: mysql:latest
   restart: unless-stopped
   ports:
     - 3306:3306
   volumes:
     - ./mysql_data:/var/lib/mysql
   environment:
     MYSQL_DATABASE: 'db'
     MYSQL_ROOT_PASSWORD: 'asdzxcfv'
     MYSQL_USER: 'el'
     MYSQL_PASSWORD: 'asdxzcfv'
   networks:
     - mysql

  phpmyadmin:
    container_name: phpmyadmin     
    image: phpmyadmin/phpmyadmin
    restart: unless-stopped
    ports:
      - 8086:80
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: 'asdzxcfv'
            
    networks:
      - mysql

    depends_on:
      - mysql
